### ISSUE TITLE
ci: converting wynncraft 101 to use mc-modpack-kit

### ISSUE THREAD

**Issue by sofiedotcafe** [aninusmuffin/wynncraft-101-old#2]
So!
It would be good if this project used [mc-modpack-kit](https://github.com/jh-devv/mc-modpack-kit).
This can be tricky e.g. the project has older versions..
So if this is "accepted", I can look into this :rocket:

**Comment by sofiedotcafe** [comment]
Needs the implementing of [release-please-action#supporting-multiple-release-branches](https://github.com/google-github-actions/release-please-action#supporting-multiple-release-branches)

**Comment by aninusmuffin** [comment]
This would be a great way to test out mc-modpack-kit in production!

There are two things that might be a problem:
- First is the previously mentioned mulit-branch support
- The second is my weird versioning scheme (`version+mcversion.modloader`) 
But im fully in support of this :D

**Comment by sofiedotcafe** [comment]
> * First is the previously mentioned mulit-branch support
@Aninuscsalas 

This is basically done, i'm yet not sure how would I make the the config for multiversioning.
Because currenly, you can just copy the main branch and change the settings in `.github/workflows/pipeline.yml` in the release please job, but this might be a problem

Maybe there would just be an .env file in `.github/workflows/` and it just picks it.
But since it happens every pull idk.

The template is desinged for people who don't know anything about GitHub actions so where I basically would I store it) (If you understand what I mean)

Have any more ideas?

**Comment by sofiedotcafe** [comment]
@Aninuscsalas About the versioning, semantic versions don't support usually this, but the most easy solution would just when uploading to modrinth, it would just add them? Is this good?

**Comment by aninusmuffin** [comment]
> @Aninuscsalas About the versioning, semantic versions don't support usually this, but the most easy solution would just when uploading to modrinth, it would just add them? Is this good?

I think this is the most reasonable solution. Anything more would be way too overkill imo.

> Have any more ideas?

Nope. Im still not sure how github works 😅

**Comment by sofiedotcafe** [comment]
@Aninuscsalas The support for multibranch and release names has been merged into *mc-modpack-kit*!
Can I start this?

**Comment by aninusmuffin** [comment]
Sure :)

**Comment by sofiedotcafe** [comment]
@Aninuscsalas 

> Sure :)

What about like current the wynncraft-101 version?
Easiest would be to start from 1.0.0 like again idk

**Comment by aninusmuffin** [comment]
I'm not sure, the pack is still in beta, maybe start from 0.1.0.

Also most updates are going to be patch/simple update releases. Soo the changelogs might be empty most of the time. :/

Btw is there any way to set mc-modpack-kit to release the modpack as beta version?

**Comment by sofiedotcafe** [comment]
> Btw is there any way to set mc-modpack-kit to release the modpack as beta version?

Not yet,
But you can still configure it manually by adding the flags to the pipeline file
(I can do that tomorrow if you want 😊)

**Comment by sofiedotcafe** [comment]
@Aninuscsalas Beta support has been added!

**Comment by sofiedotcafe** [comment]
@Aninuscsalas Can you add me as a collaborator on Modrinth and here?

**Comment by aninusmuffin** [comment]
> @Aninuscsalas Can you add me as a collaborator on Modrinth and here?

sure!

**Comment by sofiedotcafe** [comment]
@Aninuscsalas do you have the "raw" packiwz pack?

**Comment by aninusmuffin** [comment]
@jh-devv you mean this? https://github.com/Aninuscsalas/wynncraft-101/tree/packwiz

**Comment by sofiedotcafe** [comment]
@Aninuscsalas do you plan on deploying 1.12.2 anymore?

**Comment by sofiedotcafe** [comment]
#4
